- name: Importing specific distro variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
  tags:
    - vars
    - always

- name: Including unbound role if needed
  include_role: 
    name: unbound
  when: postfix_local_dns_cache
  tags:
    - resolver

- name: Ensuring that postfix pkgs are installed
  yum:
    name: "{{ postfix_pkgs }}"
    state: latest

- name: FAS helpers for virtusertable
  include_tasks: fas-aliases.yml
  when: postfix_fas_aliases

- name: FASJSON helpers for virtusertable
  include_tasks: fasjson-aliases.yml
  when: postfix_fasjson_aliases
  tags:
    - fasjson
    
- name: TLS files for postfix
  include_tasks: tls.yml
  when: postfix_tls_enable

- name: Configure postfix master.cf (Adding policyd for SPF)
  template: 
    src: "el{{ ansible_distribution_major_version }}/master.cf.j2" 
    dest: /etc/postfix/master.cf
    mode: 0644
  notify: restart_postfix
  tags:
    - config 

- name: Configure postfix main.cf
  template: 
    src: "el{{ ansible_distribution_major_version }}/main.cf.j2"
    dest: /etc/postfix/main.cf
    mode: 0644
  notify: restart_postfix
  tags:
    - config

- name: Configure postfix transport
  template: 
    src: transport.j2 
    dest: /etc/postfix/transport
    mode: 0644
  notify: postmap_transport
  tags:
    - config

- name: Configure postfix access table
  template: 
    src: access.j2 
    dest: /etc/postfix/access
    mode: 0644
  notify: postmap_access
  tags:
    - config

- name: Configure aliases table
  template: 
    src: aliases.j2 
    dest: /etc/aliases
    mode: 0644
  notify: postfix_newaliases
  tags:
    - config

- name: Configure postfix relay_recipient
  template: 
    src: relay_recipients.j2 
    dest: /etc/postfix/relay_recipients
    mode: 0644
  notify: postmap_relay_recipients
  when: postfix_filter_recipients

- name: Configure SFP python policy
  template: 
    src: policyd-spf.conf.j2
    dest: /etc/python-policyd-spf/policyd-spf.conf
    mode: 0644
  notify: restart_postfix
  tags:
    - spf

- name: Opening up smtpd
  include_role:
    name: iptables
    tasks_from: custom-policy
  vars:
    iptables_policy_name: smtpd
    iptables_protocol: tcp
    iptables_port: "25"
    iptables_source: "0.0.0.0/0"
  when: postfix_public
  tags:
    - iptables

- name: Opening up smtpd over ipv6
  include_role:
    name: iptables
    tasks_from: custom-policy-ipv6
  vars:
    iptables_policy_name: smtpd
    iptables_protocol: tcp
    iptables_port: "25"
    iptables_source: "::/0"
  when: postfix_public
  tags:
    - iptables

- name: Postfix should be enabled and running
  service:
    name: postfix
    state: started
    enabled: true

- name: Ensuring backup user and jobs
  include_role:
    name: centos-backup
    tasks_from: client
  vars:
    - centos_role: postfix
    - role_backup_folders:
        - /var/spool/postfix
  tags:
    - backup
