- name: Ensuring that postfix is installed
  yum:
    name: postfix
    state: installed

- name: Ensuring postfix will use TLS (client part)
  blockinfile:
    path: /etc/postfix/main.cf
    block: |
     # TLS - client part
     smtp_tls_CAfile=/etc/pki/tls/certs/ca-bundle.crt
     smtp_tls_security_level = may
     smtp_tls_loglevel = 1
     smtp_tls_mandatory_protocols = !SSLv2, !SSLv3
     smtp_tls_protocols = !SSLv2, !SSLv3
  notify: restart_postfix

- name: Adding relayhost info 
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: '^relayhost'
    line: "relayhost = [{{ postfix_relay_to_hostname }}]"
  when: postfix_relay_to  
  notify: restart_postfix

- name: Enabling listening on all interfaces 
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: '^inet_interfaces'
    line: "inet_interfaces = all"
  when: postfix_relay_to  
  notify: restart_postfix

- name: Configure postfix access table
  template: 
    src: access.j2 
    dest: /etc/postfix/access
  notify: postmap_access
  tags:
    - config

- name: Postfix should be enabled and running
  service:
    name: postfix
    state: started
    enabled: true



